name: The Rebel Guru
favicon: null
layout_spectrum: 0.23495
typography_spectrum: 0.33701
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fecd80'
    - '#348ab9'
    - '#ff6b2d'
    - '#7ad5c4'
    - '#1e355f'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
