name: The Rebel Guru
favicon: null
layout_spectrum: 0.34684193530119956
typography_spectrum: 0.4800924335140735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.06908615888096392
  lightness: 0.5820687315426767
  saturation: 0.592676569474861
  rhythmicContrast: 0.9393977194558829
purpose: []
